config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }
  resources :users, only: [:index, :show, :edit, :update]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    resources :lessons, except: [:index] do
      resources :comments, only: [:create, :destroy]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
  end
  resources :enrollments do
    get :my_students, on: :collection
  end
  resources :youtube, only: :show
  resources :tags, only: [:index, :create, :destroy]

  root "home#index"
  get "activity", to: "home#activity"
  get "statistics", to: "home#statistics"
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  extend FriendlyId
  friendly_id :to_s, use: :slugged

  belongs_to :course, counter_cache: true
  belongs_to :user, counter_cache: true

  validates :user, :course, presence: true
  validates_uniqueness_of :user_id, scope: :course_id
  validates_uniqueness_of :course_id, scope: :user_id
  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?
  validate :cant_subscribe_to_own_course

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }
  scope :reviewed, -> { where.not(review: [0, nil, ""]) }
  scope :latest_reviews, -> { order(rating: :desc, created_at: :desc).limit(3) }

  def to_s
    user.to_s + " " + course.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  after_destroy do
    course.update_rating
  end

  protected

  def cant_subscribe_to_own_course
    if self.new_record?
      if self.user_id.present?
        if user_id == course.user_id
          errors.add(:base, "You can't subscribe to your own course.")
        end
      end
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :set_course, only: [:new, :create]

  def index
    @ransack_path = enrollments_path
    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))

    authorize @enrollments
  end

  def show
  end

  def new
    @enrollment = Enrollment.new
  end

  def edit
    authorize @enrollment
  end

  def create
    if @course.price > 0
      flash[:alert] = "You can't access paid courses yet."
      redirect_to new_course_enrollment_path(@course)
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "Enrollment successful!"
    end
  end

  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def my_students
    @ransack_path = my_students_enrollments_path
    @q = Enrollment.joins(:course).where(courses: { user: current_user }).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render "index"
  end

  private

  def set_course
    @course = Course.friendly.find(params[:course_id])
  end

  def set_enrollment
    @enrollment = Enrollment.friendly.find(params[:id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:rating, :review)
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.haml
.card
  .card-header
    .fa.fa-user
    = link_to enrollment.user.username, user_path(enrollment.user)
    .fa.fa-clock
    = time_ago_in_words(enrollment.updated_at)
    ago
    .fa.fa-graduation-cap
    = link_to enrollment.course, course_path(enrollment.course)
  .card-body
    .fa.fa-star
    = enrollment.rating
    %br
    .fa.fa-comment
    = enrollment.review
  - if current_user
    .card-footer
      = link_to 'Back', course_path(enrollment.course)
      - if policy(enrollment).edit?
        %br
        = link_to 'Edit review', edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :rating, collection: 1..5, as: :radio_buttons
    = f.input :review

  .form-actions
    = f.button :submit, "Submit Review"

app/views/enrollments/edit.html.haml
- content_for :title do
  Edusite
  |
  Edit Review


.card
  .card-header
    #h1.h3
      .fa.fa-book
      Review Edit
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show Review', @enrollment
    \|
    = link_to 'Back to Course', course_path(@enrollment.course)

app/views/enrollments/index.html.haml
- content_for :title do
  Edusite
  |
  = action_name.humanize
  enrollments

%h1.text-center.h3.my-3
  = action_name.humanize
  enrollments
  .badge.badge-dark
    = @enrollments.count

= search_form_for @q, url: @ransack_path do |f|
  = f.search_field :user_email_cont, placeholder: "user email"
  = f.search_field :course_title_cont, placeholder: "course"
  = f.search_field :price_eq, placeholder: "price"
  = f.search_field :rating_eq, placeholder: "rating"
  = f.search_field :review_cont, placeholder: "review"
  = f.submit :Filter, class: "btn btn-sm btn-primary"
  = link_to 'Refresh', @ransack_path, class: "btn btn-sm btn-primary"

.table-responsive.mt-3
  %table.table.table-bordered.table-striped.table-sm
    %thead
      %tr
        %th= sort_link(@q, :id)
        %th= sort_link(@q, :user_email, "User")
        %th= sort_link(@q, :created_at)
        %th= sort_link(@q, :course_title, "Course")
        %th= sort_link(@q, :price)
        %th= sort_link(@q, :rating)
        %th= sort_link(@q, :review)
        %th= sort_link(@q, :updated_at)
        %th= sort_link(@q, :progress)
        %th
        %th
        %th

    %tbody
      - @enrollments.each do |enrollment|
        %tr
          %td= enrollment.id
          %td= link_to enrollment.user, user_path(enrollment.user)
          %td= enrollment.created_at.strftime("%d-%b-%Y, %H:%M")
          %td= link_to enrollment.course, course_path(enrollment.course)
          %td= number_to_currency(enrollment.price)
          %td= enrollment.rating
          %td= enrollment.review
          %td
            - if enrollment.rating.present?
              = enrollment.updated_at.strftime("%d-%b-%Y, %H:%M")
          %td= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0)
          %td= link_to 'See review', enrollment
          %td
            - if policy(enrollment).edit?
              = link_to 'Edit review', edit_enrollment_path(enrollment)
          %td
            - if policy(enrollment).destroy?
              = link_to 'Cancel enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }

!= pagy_bootstrap_nav(@pagy)

app/views/enrollments/new.html.haml
- content_for :title do
  Edusite
  |
  New Enrollment

.card
  .card-header
    #h1.h3
      .fa.fa-book
      Enroll to a course -
      = link_to @course.title, course_path(@course)
  .card-body
    = form_tag course_enrollments_path(@course) do
      = label_tag
      = submit_tag "Enroll for #{number_to_currency(@course.price)}", class: "btn btn-sm btn-primary"

  .card-footer
    = link_to 'Back', course_path(@course)

app/views/enrollments/show.html.haml
= render 'enrollments/enrollment', enrollment: @enrollment