config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }
  resources :users, only: [:index, :show, :edit, :update]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    resources :lessons, except: [:index] do
      resources :comments, only: [:create, :destroy]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
  end
  resources :enrollments do
    get :my_students, on: :collection
  end
  resources :youtube, only: :show
  resources :tags, only: [:index, :create, :destroy]

  root "home#index"
  get "activity", to: "home#activity"
  get "statistics", to: "home#statistics"
end

app/views/layouts/_footer.html.haml
%footer
  %hr.m-0.mt-3
  %div.bg-light
    .container
      .row
        .col-md-4
          Copyright
          &copy;
          = Time.now.year
          Edusite
          .row
          .fa.fa-envelope
          = mail_to "example@example.com"
          .row
        .col-md-4
          Privacy policy
          .row
          Terms and conditions
        .col-md-4
          About us
          .row
          = link_to 'Teach on Edusite', new_course_path

app/views/layouts/_google_analytics.html.haml
/ Global site tag (gtag.js) - Google Analytics
%script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=#{Rails.application.credentials.dig(:google_analytics)}"}
:javascript
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '#{Rails.application.credentials.dig(:google_analytics)}');

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    %a.navbar-brand{:href => "/"}
      = image_tag 'favicon.ico', size: "20x20", alt: "logo"
      Edusite
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      - if current_user
        %ul.navbar-nav.mr-auto
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
            = link_to root_path, class: 'nav-link' do
              .fa.fa-home
              Home
          %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
            = link_to courses_path, class: 'nav-link' do
              .fa.fa-graduation-cap
              Courses

          - if current_user.has_role?(:student)
            %li.nav-item.dropdown
              %a#studentDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                .fa.fa-user-graduate
                Student
              .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "studentDropdown"}
                = link_to purchased_courses_path, class: "dropdown-item" do
                  .fa.fa-graduation-cap
                  Purchased Courses
                  .badge.badge-dark
                    = current_user.enrollments_count
                = link_to pending_review_courses_path, class: "dropdown-item" do
                  .fa.fa-comment-dots
                  Pending Review
                  .badge.badge-dark
                    = current_user.enrollments.pending_review.count

          - if current_user.has_role?(:teacher)
            %li.nav-item.dropdown
              %a#teacherDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                .fa.fa-chalkboard-teacher
                Teacher
              .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "teacherDropdown"}
                = link_to new_course_path, class: "dropdown-item" do
                  .fa.fa-plus
                  New Course
                = link_to created_courses_path, class: "dropdown-item" do
                  .fa.fa-graduation-cap
                  Created Courses
                  .badge.badge-dark
                    = current_user.courses_count
                = link_to my_students_enrollments_path, class: "dropdown-item" do
                  .fa.fa-users
                  My Students
                  .badge.badge-dark
                    = Enrollment.joins(:course).where(courses: { user: current_user }).count

          - if current_user.has_role?(:admin)
            %li.nav-item.dropdown
              %a#adminDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                .fa.fa-user-cog
                Admin
              .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "adminDropdown"}
                = link_to users_path, class: "dropdown-item" do
                  .fa.fa-users
                  Users
                  .badge.badge-dark
                    = User.count
                = link_to enrollments_path, class: "dropdown-item" do
                  .fa.fa-book
                  Enrollments
                  .badge.badge-dark
                    = Enrollment.count
                = link_to unapproved_courses_path, class: "dropdown-item" do
                  .fa.fa-graduation-cap
                  Unapproved Courses
                  .badge.badge-dark
                    = Course.published.unapproved.count
                = link_to activity_path, class: "dropdown-item" do
                  .fa.fa-bell
                  Activity
                = link_to statistics_path, class: "dropdown-item" do
                  .fa.fa-chart-area
                  Statistics
                = link_to tags_path, class: "dropdown-item" do
                  .fa.fa-hashtag
                  Tags

        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          .input-group
            = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
            %span.input-group-ap
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}

        %ul.navbar-nav.mr-right.ml-2
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %b= current_user.email
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
              = link_to user_path(current_user), class: "dropdown-item" do
                .fa.fa-user
                My profile
              = link_to edit_user_registration_path, class: "dropdown-item" do
                .fa.fa-cog
                Account settings
              = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
                .fa.fa-sign-out-alt
                Sign out
      - else
        %ul.navbar-nav.mr-auto
        %ul.navbar-nav.mr-right
          %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
          %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'
          %li.nav-item
            = link_to user_google_oauth2_omniauth_authorize_path, class: 'nav-link' do
              .fab.fa-google
              Google OAuth
          %li.nav-item
            = form_with(url: new_user_session_path, scope: :user, local: true) do |f|
              = f.hidden_field :email, class: 'form-control', value: "admin@example.com"
              = f.hidden_field :password, class: 'form-control', value: "admin@example.com"
              = f.submit "GUEST USER", class: 'nav-link btn btn-secondary text-white'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{author: "Wojciech Lech"}
    %meta{description: "Demo online learning platform"}
    %title
      = content_for?(:title) ? yield(:title) : "Edusite"
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    - if Rails.env.production?
      = render 'layouts/google_analytics'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
    %br
    = render 'layouts/footer'